services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha_service
    restart: always
    ports:
      - "3008:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_NOWEB_WA_VERSION=auto-web
      - WAHA_NOWEB_WA_VERSION_FORCE=True
      - WAHA_ZIP_JSON_VALUE=True
      - WAHA_PRINT_QR=True
      - WAHA_LOG_LEVEL=info
      - WAHA_NO_API_KEY=True
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
      - WHATSAPP_HOOK_URL=http://backend:8000/api/business/whatsapp/webhook
      - WHATSAPP_HOOK_EVENTS=message
      - WAHA_LOCAL_STORE_BASE_DIR=/app/.sessions
    volumes:
      - waha_sessions:/app/.sessions
    networks:
      - receptionist_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - WAHA_BASE_URL=http://waha:3000
    depends_on:
      - waha
    networks:
      - receptionist_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://80.225.243.232:8000}
    container_name: frontend_service
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - receptionist_net

volumes:
  waha_sessions:

networks:
  receptionist_net:
    driver: bridge